[build]
command = "bundle exec middleman build"
publish = "build/"

[[redirects]]
  from = "/download/*"
  to = "https://s3-ap-northeast-1.amazonaws.com/bdash-release/:splat"
  status = 200
  force = true
